version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3300:3000
    networks:
      - pzfinal
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - pzfinal
networks:
  pzfinal:
volumes:
  mongodb_data:
